### ISSUE TITLE
Add a way to change translation parameters for frameworks

### ISSUE THREAD

**Issue by SeinopSys** [kirschbaum-development/laravel-translations-loader#1]
I gave this package a shot and by the looks of it there's no mechanism to replace Laravel's `:param` syntax in strings with what i18next expects (`{{param}}`).

I understand that adding something like this this globally & automatically may not be beneficial as `"string :paramcontinue"` would be perfectly valid in Laravel and only `:param` would be replaced if `[ ":param" => $value ]` was passed to it in PHP, but adding an option for a regex replace or a "filtering" function that can be stuck between the reading and bundling of translation values would be appreciated.

**Comment by luisdalmolin** [comment]
@SeinopSys I have one example I can share with you on how to use the laravel translation parameters. Which translation package are you using?

**Comment by SeinopSys** [comment]
I use `react-i18next`. For the time being I opted to use its parameter syntax in the php translations files, but that's not great if I have to share those strings with Laravel later on.

**Comment by luisdalmolin** [comment]
@SeinopSys Right, makes sense. It's definitely something useful for the package. We'll see when we can make it happen. Otherwise feel free to send a PR anytime.

**Comment by luisdalmolin** [comment]
@SeinopSys I just published a new version (0.3.0) with the ability to change the parameter syntax if you want to give a try: https://github.com/kirschbaum-development/laravel-translations-loader#replacing-laravel-parameters
