### ISSUE TITLE
Issue with loading translations from nested folders

### ISSUE THREAD

**Issue by Morinohtar** [kirschbaum-development/laravel-translations-loader#23]
Hi,

Using Laravel 7.x and the v1.0.2 version of this package.

I'm having an issue when generating translations in nested folders.

Example:

Inside the `lang/en` folder I have a folder called `admin` and here I have a file called `master.php`.

When I try to get a key from that file using `$t('admin.content.title')` it will return the string `'admin.content.title'` instead of its actual content. But if i put that same file in the root of the `lang/en` folder it will return the value correctly. I already tried some variants but so far i couldn't figure out how to go inside folders.

I tried both configs as stated in the docs:

- **First config**

**Mix:**
```
mix.extend('translations', new class {
    webpackRules() {
        return {
            test: path.resolve(__dirname, 'resources/js/lang/index.js'),
            loader: '@kirschbaum-development/laravel-translations-loader/php?parameters={$1}'
        }
    }
});

mix.translations();
```

**app.js:**
```
import languageBundle from 'resources/lang/index.js';
import VueI18n from 'vue-i18n';
Vue.use(VueI18n);

const i18n = new VueI18n({
    locale: window.Locale,
    messages: languageBundle,
})
```

- **Second config**

**app.js:**
```
import languageBundle from '@kirschbaum-development/laravel-translations-loader/php!@kirschbaum-development/laravel-translations-loader';
import VueI18n from 'vue-i18n';
Vue.use(VueI18n);

const i18n = new VueI18n({
    locale: window.Locale,
    messages: languageBundle,
})
```

Both don't work. More, the **first config** doesnt even create the content inside the `index.js` file that i created for the effect.

Could use some help. Maybe i'm doing something wrong, most likely :P

Thanks

**Comment by luisdalmolin** [comment]
@Morinohtar If you `console.log(languageBundle)` in your app.js code, what's the output you get? Do you see any translations at all?

**Comment by Morinohtar** [comment]
Did that, it only shows the lang files that are in the root folder `lang/en`, it does not go inside the folders that are also there and have files.

Let me clear a couple things that i said that are not correct:


When using the **Second config** it works fine when compiling with version `0.4.4` (but has that issue about not going inside the folders) but it gives this error when compiling using the other versions (0.5.0, 0.6.1 and 1.0.2):

```
ERROR in ./node_modules/@kirschbaum-development/laravel-translations-loader/all.js (./node_modules/@kirschbaum-development/laravel-translations-loader/php.js!./node_modules/@kirschbaum-development/laravel-translations-loader/all.js)
Module build failed (from ./node_modules/@kirschbaum-development/laravel-translations-loader/php.js):
Error: Unexpected PHP value: "bin", details: {"kind":"bin","loc":{"source":null,"start":{"line":83,"column":105,"offset":3238},"end":{"line":83,"column":222,"offset":3355}},"type":".","left":{"kind":"bin","loc":{"source":null,"start":{"line":83,"column":24,"offset":3157},"end":{"line":83,"column":222,"offset":3355}},"type":".","left":{"kind":"string","loc":{"source":null,"start":{"line":83,"column":24,"offset":3157},"end":{"line":83,"column":102,"offset":3235}},"value":"Our website uses <em>cookies</em>. You can obtain more information <a href=\"","isDoubleQuote":false},"right":{"kind":"call","loc":{"source":null,"start":{"line":83,"column":110,"offset":3243},"end":{"line":83,"column":137,"offset":3270}},"what":{"kind":"identifier","loc":{"source":null,"start":{"line":83,"column":105,"offset":3238},"end":{"line":83,"column":110,"offset":3243}},"resolution":"uqn","name":"route"},"arguments":[{"kind":"string","loc":{"source":null,"start":{"line":83,"column":111,"offset":3244},"end":{"line":83,"column":136,"offset":3269}},"value":"frontend.privacy-policy","isDoubleQuote":false}]}},"right":{"kind":"string","loc":{"source":null,"start":{"line":83,"column":140,"offset":3273},"end":{"line":83,"column":222,"offset":3355}},"value":"\" class=\"font-italic\">here</a>. In order to use the website properly, please ...","isDoubleQuote":false}}

```

When using the **First config** it compiles properly with all versions but the `index.js` that i created to receive the data remains empty.

**Comment by luisdalmolin** [comment]
@Morinohtar Yeah, to load from nested folders you will have to be on the latest version. Also, the `index.js` file you've created is not going to receive any content, it only serves as a "fake" to tell webpack where your language files are located, basically.

Any change you can post your lang file in here? It seems that some content in there is failing to parse. By any chance, you have any PHP code in the language file? Can you post the content here?

**Comment by Morinohtar** [comment]
That was it, dumb of me. 
I had in a couple of lang files the `route()` function. Not a good practice having this type of code inside the lang files. 
Already corrected and everything is working properly (in both types of configs) ;)

Tks :)

**Comment by luisdalmolin** [comment]
Great, that's good to hear it's working now. I'll close this issue.
