### ISSUE TITLE
Load specific translations

### ISSUE THREAD

**Issue by andreyberezhnoy** [kirschbaum-development/laravel-translations-loader#25]
Can I load specific translations (not all)?

For example:

I want to load only `resources/lang/auth.php`

**Comment by luisdalmolin** [comment]
@andreyberezhnoy This is not possible at this point, but a PR adding this would be accepted. You basically would need to add a new option to the webpack loader.

**Comment by luisdalmolin** [comment]
@andreyberezhnoy this was implemented in version 1.3.0:

https://github.com/kirschbaum-development/laravel-translations-loader/releases/tag/1.3.0
