### ISSUE TITLE
Using fallback translations

### ISSUE THREAD

**Issue by sebastiaanluca** [kirschbaum-development/laravel-translations-loader#26]
In Laravel/Blade, when a language does not contain a translation string, [the translation of the fallback language is used](https://laravel.com/docs/8.x/localization#configuring-the-locale). This doesn't seem the case with this package and simply returns the key itself. To work around this, we'd either have to maintain a single JSON translation file for all our different backoffices or translate every single key. However neither is an ideal solution.

How trivial would it be to implement this and to submit a PR? Not entirely familiar with how the code works. I guess the user would have to set the fallback translation when requiring the package and we'd have to try and load the fallback translation by key if none is present for the active language? We're using `VueI18n` so not sure how that would work together.

**Comment by sebastiaanluca** [comment]
Nevermind. Possible with https://kazupon.github.io/vue-i18n/guide/fallback.html#implicit-fallback-using-locales 😅

**Comment by luisdalmolin** [comment]
Yeah, this is a feature that the i18n library needs to have. Glad you solved it.
