### ISSUE TITLE
Not working with version ^0.4.0

### ISSUE THREAD

**Issue by SamuelNitsche** [kirschbaum-development/laravel-translations-loader#4]
I don't get the package working with the latest version.
The console logs following error
![bildschirmfoto 2018-10-17 um 14 25 45](https://user-images.githubusercontent.com/24483576/47086006-a25f4200-d218-11e8-800f-8a48d5373261.png)

When I use version ^0.3.0 everything works fine.

![bildschirmfoto 2018-10-17 um 14 27 01](https://user-images.githubusercontent.com/24483576/47086043-bf941080-d218-11e8-93d6-cf3e97d984eb.png)

**Comment by luisdalmolin** [comment]
@SamuelNitsche can you post the code you are using to import the files? I'll take a look soon at this.

**Comment by SamuelNitsche** [comment]
Of course. This is the code I use.

![bildschirmfoto 2018-10-18 um 08 35 35](https://user-images.githubusercontent.com/24483576/47135519-ddad4f80-d2b0-11e8-9d73-c42fae473a81.png)
![bildschirmfoto 2018-10-18 um 08 35 44](https://user-images.githubusercontent.com/24483576/47135520-de45e600-d2b0-11e8-8480-b7aeab30d041.png)

**Comment by luisdalmolin** [comment]
@SamuelNitsche Hey, thanks for reporting the issue. Indeed there was an error with the 0.4.0 version. I just pushed and tagged 0.4.1, can you test?

**Comment by SamuelNitsche** [comment]
Yeah, now it works perfectly fine. Thank you!

**Comment by luisdalmolin** [comment]
@atharhashmi can you post the code you are using to import the translations? Also, are you using different paths for the react files or the translations files?

**Comment by atharhashmi** [comment]
Thanks a lot for your response. No, I am using the default path where Laravel keeps the translation files, i.e. `resources/lang/en`.
All I did was the following, nothing fancy:

1. `npm install @kirschbaum-development/laravel-translations-loader --save-dev`
2. `import languageBundle from '@kirschbaum-development/laravel-translations-loader?namespace=common!@kirschbaum-development/laravel-translations-loader';`
3. `console.log(languageBundle);`

Did I miss anything?

**Comment by luisdalmolin** [comment]
@atharhashmi everything seems correct - I'll make one local test here to make sure? Are you using laravel-mix? Which version? Otherwise which webpack version you are using?

**Comment by atharhashmi** [comment]
I am using Laravel Mix. Here are the details:

1. Laravel Mix - 2.1.14
2. Node: 8.11.3
3. NPM: 6.4.1

**Comment by luisdalmolin** [comment]
@atharhashmi I just tried with almost the same settings and worked - What is the full path of the JS file you are trying to import the language bundle?

**Comment by atharhashmi** [comment]
Hi @luisdalmolin do you mean the file I am calling the bundle in? I will go ahead and give you the details, let me know if there is anything else you are looking for:
- **JS file where the bundle is being imported:** resources/js/index.js - the `console.log` screenshot I sent earlier was from this file.
- **Translation files:** resources/lang/en/auth.php|pagination.php|passwords.php|validation.php
- **Path of the package:** node_modules/@kirschbaum-development/laravel-translation-loader

**Comment by atharhashmi** [comment]
There you go...

`const _ = require('lodash');`
`const phpLoader = require('./php-loader');`
`const jsonLoader = require('./json-loader');`
`const loaderUtils = require('loader-utils');`
`module.exports = function (indexContent) {
    let options = {};
    let baseDirectory;`

    `try {
        options = loaderUtils.parseQuery(this.query);
    } catch (e) { }

    if (path.dirname(this.resource).includes(path.dirname('node_modules/@kirschbaum-development/laravel-translations-loader/all.js'))) {
        baseDirectory = path.dirname(this.resource) + "/../../../resources/lang";
    } else {
        baseDirectory = path.dirname(this.resource);
    }

    this.addDependency(baseDirectory);

    const jsonContents = jsonLoader.execute(baseDirectory, options);
    const phpContents = phpLoader.execute(baseDirectory, options);
    const bundle = _.merge(phpContents, jsonContents);

    return "module.exports = " + JSON.stringify(bundle);`
`}`

**Comment by atharhashmi** [comment]
Looks like I am on 0.4.1, At least this is what I have in my package.json

![image](https://user-images.githubusercontent.com/22662163/51390511-4ecefe00-1b51-11e9-8942-a0cc4ccc2b49.png)

**Comment by luisdalmolin** [comment]
@atharhashmi ok so I'm not sure what's going on. So if you can push the code to a repository I can try to find the problem. You can just include your translations files, webpack.mix, package.json and JS files and that should be enough.

**Comment by atharhashmi** [comment]
I can do that, but first, here are the contents of my webpack.mix.js. Do you see any problems with this?

```
const mix = require('laravel-mix');

mix.react('resources/js/app.js', 'public/js')
    .webpackConfig({
        resolve: {
            modules: [
                'node_modules',
                'resources/js'
            ]
        }
    })
    .sass('resources/sass/app.scss', 'public/css');
```

**Comment by atharhashmi** [comment]
@luisdalmolin 
OK, it gets even more strange... I cloned your repository, ran the following:
- composer update
- npm install
- npm run watch
php artisan serve

and attached is what I see, SAME PROBLEM....

You think it may be due to the PHP version I am using? Or may be because I am using `php artisan serve`?

![image](https://user-images.githubusercontent.com/22662163/51409178-daad4e00-1b82-11e9-899c-0b4bcf4aead6.png)

**Comment by luisdalmolin** [comment]
@atharhashmi I believe this is related to the Node version. I'll make some tests tonight/tomorrow morning using Node 8.

**Comment by atharhashmi** [comment]
Hi @luisdalmolin , Just for your information, I updated my node version to the latest 11.7.0 with no success, same results. Please let me know if you find something.

Thanks again for all your help!

**Comment by luisdalmolin** [comment]
@atharhashmi on the screenshot you posted, there's a line called `LANG FILE` in the console.log. Did you add this? Because the test repo don't have that

**Comment by luisdalmolin** [comment]
@atharhashmi so that's the only change you made in my repo and is not working? I would like to replicate this and fix this bug, but I can't replicate here. I also tested with Node 8 over the weekend and it worked.

**Comment by luisdalmolin** [comment]
@atharhashmi other thing you can try is to specify the translations folder. For this, you have to create an empty `index.js` file in `resources/lang`, and import the file with the following syntax:

```js
!../lang
```

I also pushed an updated test to the test repo: https://github.com/luisdalmolin/laravel-translations-loader-test/blob/master/resources/js/app.js

**Comment by atharhashmi** [comment]
That's it. **It worked!** Here is what I did:
1. Imported the package like `import languageBundle from "@kirschbaum-development/laravel-translations-loader?namespace=common!@kirschbaum-development/laravel-translations-loader!./../lang/index.js";`
2. Created an empty `index.js` in `resources/lang/`

Awesome, I can't thank you enough... How can I buy you a bear?

**Comment by luisdalmolin** [comment]
@atharhashmi just give a star to the package and I'm happy enough :)) - or if you end up in Laracon US this year we can have a beer 🍻

**Comment by atharhashmi** [comment]
I just starred the package. Thanks again. 

Laracon US, no. However, I will be around NYC/DC in around mid of April this year. And I owe you a bear 👍

**Comment by atharhashmi** [comment]
Hi @luisdalmolin 

Quick question, how can I define both `namespace` and `parameters` in the import statement?

I currently have the following statement and I don't understand how to insert the `parameter` directive.

`import languageBundle from "@kirschbaum-development/laravel-translations-loader?namespace=common!@kirschbaum-development/laravel-translations-loader!./../../lang/index.js";
`

**Comment by luisdalmolin** [comment]
@atharhashmi I just merged a PR and tagged 0.6.0 which should fix this issue. Let me know if it works.

**Comment by atharhashmi** [comment]
Thanks for the update @luisdalmolin 

However, I am struggling with the import statement. Could you give an example of how we should use both `namespace` and `parameters` in the same import statement? I tried the following but it breaks my `npm run watch`...

`import languageBundle from "@kirschbaum-development/laravel-translations-loader?parameters={{ $1 }}!namespace=common!@kirschbaum-development/laravel-translations-loader!./../../lang/index.js";
`

**Comment by luisdalmolin** [comment]
Sure, that would become:

```js
import languageBundle from "@kirschbaum-development/laravel-translations-loader?parameters={{ $1 }}&namespace=common!@kirschbaum-development/laravel-translations-loader!./../../lang/index.js";
```

Like a query string. Let me know if that works.

**Comment by atharhashmi** [comment]
@luisdalmolin , I should have mentioned that I had already tried that. It didn't work I am afraid. I see the following error on npm run watch. Just an FYI, I tried switching places for parameters and namespace (place namespace before parameters).
```
ERROR in ./node_modules/@kirschbaum-development/laravel-translations-loader/all.js?namespace=common&parameters={{ $1 }}!./node_modules/@kirschbaum-development/laravel-translations-loader/all.js!./resources/lang/index.js
Module build failed: TypeError: bundle[directory][options.namespace].replace is not a function
    at files.forEach (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\php-loader.js:44:101)
    at Array.forEach (<anonymous>)
    at directories.forEach (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\php-loader.js:24:19)
    at Array.forEach (<anonymous>)
    at Object.execute (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\php-loader.js:18:21)
    at Object.module.exports (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\all.js:24:35)
 @ ./resources/js/components/App.js 33:0-192
 @ ./resources/js/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

**Comment by luisdalmolin** [comment]
@atharhashmi are you running version 0.6.0?

**Comment by atharhashmi** [comment]
I am on 0.6.0. The item in my package.json is:
`"@kirschbaum-development/laravel-translations-loader": "^0.6.0",`

and the error I receive is:
```
ERROR in ./node_modules/@kirschbaum-development/laravel-translations-loader/all.js?parameters={{$1}}&namespace=common!./node_modules/@kirschbaum-development/laravel-translations-loader/all.js!./resources/lang/index.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at klaw.filter.forEach (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\php-loader.js:30:52)
    at Array.forEach (<anonymous>)
    at directories.forEach (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\php-loader.js:28:16)
    at Array.forEach (<anonymous>)
    at Object.execute (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\php-loader.js:21:21)
    at Object.module.exports (E:\xampp7\htdocs\briefingsource-v3\node_modules\@kirschbaum-development\laravel-translations-loader\all.js:25:35)
 @ ./resources/js/components/App.js 29:0-190
 @ ./resources/js/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
```

**Comment by luisdalmolin** [comment]
@atharhashmi do you have the `resources/lang/index.js` file created? Looks a weird error. Also, are you on windows?

**Comment by atharhashmi** [comment]
Hey, I do have a `resources/lang/index.js` file (its empty though). and yes, I am on Windows 10.

**Comment by kovinet** [comment]
I still have this issue on Windows while working fine on Ubuntu. I have latest version 1.0.2.
I created empty `resources/lang/index.js` tried using alternative method with updating webpack mix file as in instructions but still get same error..

**Comment by kovinet** [comment]
If I run it inside WSL terminal it then works. But since I am still on WSL 1 this makes my builds quite slow.
Any ideas why is path undefined on windows and is there an easy fix?

**Comment by luisdalmolin** [comment]
@kovinet What is the Laravel mix version you are using? Any chances you can push your code or just a simulation that fails so I can take a look?

**Comment by kovinet** [comment]
I am using Laravel Mix version v4.0.14. While checking the versions I see that there is v5.0.0 available now. I will try with v5 if it works, otherwise I will provide you with example code..

**Comment by kovinet** [comment]
I have pushed relevant parts of my Laravel project to https://github.com/kovinet/laravel-js-translate-example

But after updating my packages (`yarn upgrade`) problem was resolved. I am not sure which package was causing the problem, but it is working now. So I guess you can again close this issue :)

**Comment by luisdalmolin** [comment]
Ok, that's good. Closing this again, thanks.
