### ISSUE TITLE
How to use this with Vite?

### ISSUE THREAD

**Issue by JVT038** [kirschbaum-development/laravel-translations-loader#41]
When I try to use this with Vite, Vite can't resolve this import.
I'm using this code to import: `import languageBundle from '@kirschbaum-development/laravel-translations-loader/php!@kirschbaum-development/laravel-translations-loader'`

This results in this error:
```
[plugin:vite:import-analysis] Failed to resolve import "@kirschbaum-development/laravel-translations-loader/php!@kirschbaum-development/laravel-translations-loader" from "resources\js\app.js". Does the file exist?
```

**Comment by luisdalmolin** [comment]
This package won't work with Vite unfortunately, as it is a Webpack loader. It can definitely be ported to Vite, just not in the current plans.
