### ISSUE TITLE
'path is not defined' when using laravel-translations-loader with vue-cli

### ISSUE THREAD

**Issue by brobyns** [kirschbaum-development/laravel-translations-loader#8]
I'm trying to use laravel-translations-loader in combination with vue-cli 3. I'm getting an error 'path is not defined' on line 14 in all.js 
My code in vue.config.js is as below:

```
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('i18n')
      .test(path.resolve(__dirname, 'resources/lang/index.js'))
      .use('@kirschbaum-development/laravel-translations-loader/php?parameters={$1}')
        .loader('@kirschbaum-development/laravel-translations-loader/php?parameters={$1}')
        .end()
  }
}
```

I also tried using the configureWebpack option in vue.config.js but no luck there either. I get the same error.

```
// vue.config.js
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: path.resolve(__dirname, 'resources/lang/index.js'), // path to your index.js file
          loader:
            '@kirschbaum-development/laravel-translations-loader/php?parameters={$1}',
        },
      ],
    },
  },
}
```
Seems the 'path' dependency is not correctly loaded when using it this way.
Any ideas?

**Comment by luisdalmolin** [comment]
Hmm, I never used with vue-cli. Did you installed vue-cli boilerplate on top of a Laravel installation? Just trying to understand how I can replicate here.

**Comment by brobyns** [comment]
I'm using the setup that was presented at laracon. This is the demo project Evan You referenced: https://github.com/yyx990803/laravel-vue-cli-3

**Comment by luisdalmolin** [comment]
@brobyns I think you are just missing the path import in the vue config file. I added the following and it compiled:

```js
let path = require('path');
```

You may also need to configure the path since you are building from a different location, not sure. Let me know if that works.

**Comment by brobyns** [comment]
@luisdalmolin 
You are right. The 'path' import and properly configuring the path to index.js is all that is needed.

Don't know what went wrong with my build because the 'path' dependency was already imported in my vue.config file but anyway its working now. 
Thanks a lot!

```
const path = require('path')
module.exports = {

  chainWebpack: config => {
    config.module
      .rule('i18n')
      .test(path.resolve(__dirname, '../resources/lang/index.js'))
      .use('@kirschbaum-development/laravel-translations-loader/php?parameters={$1}')
      .loader('@kirschbaum-development/laravel-translations-loader/php?parameters={$1}')
      .end()
  },
}
```
